name: Deploy a Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout del código
        uses: actions/checkout@v3

      - name: 🔹 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔹 Instalar dependencias
        run: npm install

      - name: 🔹 Construir el proyecto
        run: npm run build

      - name: 🔹 Desplegar en Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
